export const questions = [
  { id: 1, question: "I enjoy solving logical problems", Engineering: 5, IT: 4, Medical: 2, Commerce: 2 },
  { id: 2, question: "I like writing computer programs", Engineering: 3, IT: 5, Medical: 2, Commerce: 1 },
  { id: 3, question: "Debugging code excites me", Engineering: 4, IT: 5, Medical: 1, Commerce: 1 },
  { id: 4, question: "I enjoy learning new programming languages", Engineering: 3, IT: 5, Medical: 1, Commerce: 1 },
  { id: 5, question: "I like building applications", Engineering: 4, IT: 5, Medical: 1, Commerce: 2 },
  { id: 6, question: "I like analyzing data to find patterns", Engineering: 3, IT: 5, Medical: 2, Commerce: 3 },
  { id: 7, question: "Statistics interests me", Engineering: 2, IT: 5, Medical: 2, Commerce: 3 },
  { id: 8, question: "I enjoy working with numbers", Engineering: 3, IT: 4, Medical: 2, Commerce: 4 },
  { id: 9, question: "I want to work with AI or ML", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },
  { id: 10, question: "I enjoy data visualization", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },

  { id: 11, question: "I enjoy designing user interfaces", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },
  { id: 12, question: "I like creative visual work", Engineering: 1, IT: 4, Medical: 1, Commerce: 2 },
  { id: 13, question: "I enjoy working with colors and layouts", Engineering: 1, IT: 5, Medical: 1, Commerce: 1 },
  { id: 14, question: "I like building websites", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },
  { id: 15, question: "I enjoy improving user experience", Engineering: 1, IT: 5, Medical: 1, Commerce: 1 },

  { id: 16, question: "I am interested in cybersecurity", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },
  { id: 17, question: "I like protecting systems from attacks", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },
  { id: 18, question: "I enjoy learning about computer networks", Engineering: 3, IT: 5, Medical: 1, Commerce: 1 },
  { id: 19, question: "I want to work in ethical hacking", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },
  { id: 20, question: "I am curious about system vulnerabilities", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },

  { id: 21, question: "I enjoy building machines", Engineering: 5, IT: 3, Medical: 1, Commerce: 1 },
  { id: 22, question: "I like understanding how engines work", Engineering: 5, IT: 3, Medical: 1, Commerce: 1 },
  { id: 23, question: "I enjoy working with electrical circuits", Engineering: 5, IT: 3, Medical: 1, Commerce: 1 },
  { id: 24, question: "I like electronics projects", Engineering: 5, IT: 3, Medical: 1, Commerce: 1 },
  { id: 25, question: "I enjoy physics-based problem solving", Engineering: 5, IT: 3, Medical: 1, Commerce: 1 },

  { id: 26, question: "I like managing people and tasks", Engineering: 2, IT: 2, Medical: 2, Commerce: 5 },
  { id: 27, question: "I enjoy planning and organizing work", Engineering: 2, IT: 2, Medical: 2, Commerce: 5 },
  { id: 28, question: "I like leadership roles", Engineering: 3, IT: 3, Medical: 2, Commerce: 5 },
  { id: 29, question: "I enjoy decision making", Engineering: 2, IT: 2, Medical: 2, Commerce: 5 },
  { id: 30, question: "I want to run my own business", Engineering: 2, IT: 2, Medical: 1, Commerce: 5 },

  { id: 31, question: "I enjoy working with accounts", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 32, question: "I like managing finances", Engineering: 1, IT: 2, Medical: 1, Commerce: 5 },
  { id: 33, question: "I am interested in stock markets", Engineering: 1, IT: 2, Medical: 1, Commerce: 5 },
  { id: 34, question: "I like auditing work", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 35, question: "I enjoy budgeting and cost control", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },

  { id: 36, question: "I enjoy content creation", Engineering: 1, IT: 2, Medical: 1, Commerce: 3 },
  { id: 37, question: "I like storytelling", Engineering: 1, IT: 1, Medical: 1, Commerce: 3 },
  { id: 38, question: "I enjoy social media work", Engineering: 1, IT: 2, Medical: 1, Commerce: 3 },
  { id: 39, question: "I enjoy video editing", Engineering: 1, IT: 2, Medical: 1, Commerce: 2 },
  { id: 40, question: "I like photography", Engineering: 1, IT: 2, Medical: 1, Commerce: 2 },

  { id: 41, question: "I enjoy teaching others", Engineering: 2, IT: 2, Medical: 3, Commerce: 2 },
  { id: 42, question: "I like explaining concepts", Engineering: 2, IT: 2, Medical: 3, Commerce: 2 },
  { id: 43, question: "I enjoy mentoring students", Engineering: 2, IT: 2, Medical: 3, Commerce: 2 },
  { id: 44, question: "I enjoy academic research", Engineering: 3, IT: 3, Medical: 4, Commerce: 2 },
  { id: 45, question: "I like continuous learning", Engineering: 3, IT: 3, Medical: 3, Commerce: 2 },

  { id: 46, question: "I want to help people medically", Engineering: 1, IT: 1, Medical: 5, Commerce: 1 },
  { id: 47, question: "I am interested in human biology", Engineering: 1, IT: 1, Medical: 5, Commerce: 1 },
  { id: 48, question: "I enjoy caring for patients", Engineering: 1, IT: 1, Medical: 5, Commerce: 1 },
  { id: 49, question: "I am interested in pharmacy", Engineering: 1, IT: 1, Medical: 5, Commerce: 1 },
  { id: 50, question: "I like medical research", Engineering: 2, IT: 2, Medical: 5, Commerce: 1 },

  { id: 51, question: "I enjoy laboratory experiments", Engineering: 2, IT: 1, Medical: 5, Commerce: 1 },
  { id: 52, question: "I like diagnosing problems", Engineering: 3, IT: 3, Medical: 5, Commerce: 2 },
  { id: 53, question: "I enjoy patient interaction", Engineering: 1, IT: 1, Medical: 5, Commerce: 1 },
  { id: 54, question: "I like healthcare technology", Engineering: 2, IT: 3, Medical: 5, Commerce: 1 },
  { id: 55, question: "I am interested in medical imaging", Engineering: 3, IT: 2, Medical: 5, Commerce: 1 },

  { id: 56, question: "I like robotics", Engineering: 5, IT: 4, Medical: 1, Commerce: 1 },
  { id: 57, question: "I enjoy automation systems", Engineering: 5, IT: 4, Medical: 1, Commerce: 1 },
  { id: 58, question: "I like working with sensors", Engineering: 5, IT: 3, Medical: 1, Commerce: 1 },
  { id: 59, question: "I enjoy mechanical design", Engineering: 5, IT: 2, Medical: 1, Commerce: 1 },
  { id: 60, question: "I like CAD software", Engineering: 5, IT: 3, Medical: 1, Commerce: 1 },

  { id: 61, question: "I enjoy database management", Engineering: 3, IT: 5, Medical: 1, Commerce: 3 },
  { id: 62, question: "I like backend development", Engineering: 3, IT: 5, Medical: 1, Commerce: 1 },
  { id: 63, question: "I enjoy API integration", Engineering: 3, IT: 5, Medical: 1, Commerce: 1 },
  { id: 64, question: "I like cloud computing", Engineering: 3, IT: 5, Medical: 1, Commerce: 2 },
  { id: 65, question: "I enjoy DevOps practices", Engineering: 3, IT: 5, Medical: 1, Commerce: 1 },

  { id: 66, question: "I enjoy public speaking", Engineering: 2, IT: 2, Medical: 2, Commerce: 5 },
  { id: 67, question: "I like negotiating deals", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 68, question: "I enjoy sales activities", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 69, question: "I like customer interaction", Engineering: 1, IT: 2, Medical: 2, Commerce: 5 },
  { id: 70, question: "I enjoy business strategy", Engineering: 2, IT: 2, Medical: 1, Commerce: 5 },

  { id: 71, question: "I enjoy economics", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 72, question: "I like market analysis", Engineering: 1, IT: 2, Medical: 1, Commerce: 5 },
  { id: 73, question: "I enjoy financial planning", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 74, question: "I like risk management", Engineering: 1, IT: 2, Medical: 1, Commerce: 5 },
  { id: 75, question: "I enjoy taxation topics", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },

  { id: 76, question: "I like ethical decision making", Engineering: 2, IT: 2, Medical: 4, Commerce: 3 },
  { id: 77, question: "I enjoy social responsibility work", Engineering: 1, IT: 1, Medical: 3, Commerce: 3 },
  { id: 78, question: "I like NGO involvement", Engineering: 1, IT: 1, Medical: 3, Commerce: 3 },
  { id: 79, question: "I enjoy community service", Engineering: 1, IT: 1, Medical: 4, Commerce: 2 },
  { id: 80, question: "I like health awareness programs", Engineering: 1, IT: 1, Medical: 5, Commerce: 1 },

  { id: 81, question: "I enjoy system architecture design", Engineering: 4, IT: 5, Medical: 1, Commerce: 1 },
  { id: 82, question: "I like performance optimization", Engineering: 4, IT: 5, Medical: 1, Commerce: 1 },
  { id: 83, question: "I enjoy algorithm design", Engineering: 4, IT: 5, Medical: 1, Commerce: 1 },
  { id: 84, question: "I like solving complex problems", Engineering: 5, IT: 4, Medical: 2, Commerce: 2 },
  { id: 85, question: "I enjoy competitive programming", Engineering: 4, IT: 5, Medical: 1, Commerce: 1 },

  { id: 86, question: "I enjoy quality assurance testing", Engineering: 3, IT: 4, Medical: 1, Commerce: 2 },
  { id: 87, question: "I like automation testing", Engineering: 3, IT: 5, Medical: 1, Commerce: 1 },
  { id: 88, question: "I enjoy software documentation", Engineering: 2, IT: 3, Medical: 1, Commerce: 2 },
  { id: 89, question: "I like product lifecycle management", Engineering: 3, IT: 3, Medical: 1, Commerce: 3 },
  { id: 90, question: "I enjoy technical support roles", Engineering: 2, IT: 4, Medical: 1, Commerce: 2 },

  { id: 91, question: "I enjoy hospital administration", Engineering: 1, IT: 2, Medical: 4, Commerce: 3 },
  { id: 92, question: "I like healthcare management", Engineering: 1, IT: 2, Medical: 4, Commerce: 3 },
  { id: 93, question: "I enjoy medical record analysis", Engineering: 1, IT: 2, Medical: 5, Commerce: 1 },
  { id: 94, question: "I like telemedicine platforms", Engineering: 2, IT: 3, Medical: 5, Commerce: 1 },
  { id: 95, question: "I enjoy health data analysis", Engineering: 2, IT: 4, Medical: 5, Commerce: 2 },

  { id: 96, question: "I enjoy startup environments", Engineering: 3, IT: 3, Medical: 2, Commerce: 4 },
  { id: 97, question: "I like innovation challenges", Engineering: 4, IT: 4, Medical: 2, Commerce: 3 },
  { id: 98, question: "I enjoy brainstorming ideas", Engineering: 3, IT: 3, Medical: 2, Commerce: 4 },
  { id: 99, question: "I like pitching ideas", Engineering: 2, IT: 2, Medical: 1, Commerce: 5 },
  { id: 100, question: "I enjoy startup funding concepts", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },

  { id: 101, question: "I enjoy supply chain management", Engineering: 2, IT: 2, Medical: 1, Commerce: 5 },
  { id: 102, question: "I like logistics planning", Engineering: 2, IT: 2, Medical: 1, Commerce: 5 },
  { id: 103, question: "I enjoy operations management", Engineering: 2, IT: 2, Medical: 1, Commerce: 5 },
  { id: 104, question: "I like inventory management", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 105, question: "I enjoy procurement processes", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },

  { id: 106, question: "I enjoy environmental studies", Engineering: 3, IT: 2, Medical: 3, Commerce: 2 },
  { id: 107, question: "I like sustainability projects", Engineering: 3, IT: 2, Medical: 3, Commerce: 2 },
  { id: 108, question: "I enjoy green technology", Engineering: 4, IT: 3, Medical: 2, Commerce: 2 },
  { id: 109, question: "I like climate change research", Engineering: 3, IT: 2, Medical: 3, Commerce: 2 },
  { id: 110, question: "I enjoy renewable energy topics", Engineering: 5, IT: 3, Medical: 1, Commerce: 1 },

  { id: 111, question: "I enjoy mobile app development", Engineering: 3, IT: 5, Medical: 1, Commerce: 1 },
  { id: 112, question: "I like cross-platform apps", Engineering: 3, IT: 5, Medical: 1, Commerce: 1 },
  { id: 113, question: "I enjoy UI animations", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },
  { id: 114, question: "I like frontend frameworks", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },
  { id: 115, question: "I enjoy responsive design", Engineering: 2, IT: 5, Medical: 1, Commerce: 1 },

  { id: 116, question: "I enjoy HR management", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 117, question: "I like employee engagement", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 118, question: "I enjoy talent acquisition", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 119, question: "I like organizational behavior", Engineering: 1, IT: 1, Medical: 1, Commerce: 5 },
  { id: 120, question: "I enjoy workplace psychology", Engineering: 1, IT: 1, Medical: 2, Commerce: 4 },

  { id: 121, question: "I enjoy legal studies", Engineering: 1, IT: 1, Medical: 1, Commerce: 4 },
  { id: 122, question: "I like corporate law topics", Engineering: 1, IT: 1, Medical: 1, Commerce: 4 },
  { id: 123, question: "I enjoy compliance management", Engineering: 1, IT: 1, Medical: 1, Commerce: 4 },
  { id: 124, question: "I like policy interpretation", Engineering: 1, IT: 1, Medical: 1, Commerce: 4 },
  { id: 125, question: "I enjoy regulatory frameworks", Engineering: 1, IT: 1, Medical: 1, Commerce: 4 },

  { id: 126, question: "I enjoy research writing", Engineering: 3, IT: 3, Medical: 4, Commerce: 2 },
  { id: 127, question: "I like publishing papers", Engineering: 3, IT: 3, Medical: 4, Commerce: 2 },
  { id: 128, question: "I enjoy academic conferences", Engineering: 3, IT: 3, Medical: 4, Commerce: 2 },
  { id: 129, question: "I like scholarly discussions", Engineering: 3, IT: 3, Medical: 4, Commerce: 2 },
  { id: 130, question: "I enjoy peer reviews", Engineering: 3, IT: 3, Medical: 4, Commerce: 2 },

  { id: 131, question: "I enjoy mentoring juniors", Engineering: 3, IT: 3, Medical: 3, Commerce: 3 },
  { id: 132, question: "I like guiding career paths", Engineering: 2, IT: 2, Medical: 3, Commerce: 3 },
  { id: 133, question: "I enjoy counseling students", Engineering: 1, IT: 1, Medical: 3, Commerce: 3 },
  { id: 134, question: "I like motivational speaking", Engineering: 1, IT: 1, Medical: 2, Commerce: 4 },
  { id: 135, question: "I enjoy life coaching", Engineering: 1, IT: 1, Medical: 2, Commerce: 4 },

  { id: 136, question: "I enjoy policy making", Engineering: 2, IT: 2, Medical: 3, Commerce: 4 },
  { id: 137, question: "I like governance systems", Engineering: 2, IT: 2, Medical: 3, Commerce: 4 },
  { id: 138, question: "I enjoy social reform initiatives", Engineering: 1, IT: 1, Medical: 3, Commerce: 3 },
  { id: 139, question: "I like public administration", Engineering: 1, IT: 1, Medical: 2, Commerce: 4 },
  { id: 140, question: "I enjoy civil services preparation", Engineering: 2, IT: 2, Medical: 2, Commerce: 4 },

  { id: 141, question: "I enjoy futuristic research", Engineering: 4, IT: 4, Medical: 2, Commerce: 2 },
  { id: 142, question: "I like interdisciplinary work", Engineering: 4, IT: 4, Medical: 3, Commerce: 3 },
  { id: 143, question: "I enjoy innovation labs", Engineering: 4, IT: 4, Medical: 2, Commerce: 2 },
  { id: 144, question: "I like solving global challenges", Engineering: 4, IT: 4, Medical: 3, Commerce: 3 },
  { id: 145, question: "I enjoy long-term impact projects", Engineering: 3, IT: 3, Medical: 3, Commerce: 3 },

  { id: 146, question: "I like futuristic technologies", Engineering: 3, IT: 5, Medical: 1, Commerce: 2 },
  { id: 147, question: "I enjoy mentoring startups", Engineering: 2, IT: 3, Medical: 2, Commerce: 3 },
  { id: 148, question: "I like community leadership", Engineering: 2, IT: 2, Medical: 3, Commerce: 3 },
  { id: 149, question: "I enjoy policy and governance", Engineering: 2, IT: 2, Medical: 3, Commerce: 4 },
  { id: 150, question: "I like creating impact at scale", Engineering: 3, IT: 4, Medical: 2, Commerce: 4 }
];